export {
  APP_METADATA,
  SIDEBAR_CONFIG,
  SIDEBAR_FOOTER_LINKS,
  SIDEBAR_FOOTER_STATUSES,
  SIDEBAR_GLOBAL_ACTIONS,
  SIDEBAR_GROUPS,
  SIDEBAR_NAV,
  SIDEBAR_TOP_CONTENT,
  getLiliaUiConfig,
  resolveLiliaIcon,
  setLiliaUiConfig,
  type BackdropMode,
  type BackdropTarget,
  type IconInput,
  type LiliaAppearanceConfigInput,
  type LiliaPlatformAppearanceDefaults,
  type LiliaSidebarConfigInput,
  type LiliaSidebarFooterStatusInput,
  type LiliaUiConfig,
  type NativePlatform,
  type SidebarActionItem,
  type SidebarFooterLink,
  type SidebarFooterStatus,
  type SidebarGroup,
  type SidebarNavItem,
} from "./config/appShell";
export {
  liliaShellOptionsKey,
  type LiliaShellOptions,
} from "./shellOptions";
